version: '3.9'

networks: 
  laravel:
    driver: bridge
services:
  nginx:
    # image: nginx:alpine
    image: "scout3030/nginx:${TAG:-latest}"
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes: 
      - ./src:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - db
      - phpmyadmin
    networks: 
      - laravel
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: product_master
      MYSQL_ROOT_PASSWORD: root
    ports:  
      - "3333:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/backup:/srv/backup
    networks: 
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7777:80"
    depends_on:
      - db
    networks: 
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes: 
      - ./src:/var/www/app
    ports: 
      - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
      - "5713:5713"
    networks: 
      - laravel
  